# Generated by Django 3.1.5 on 2021-01-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50, null=True)),
                ('google_account', models.CharField(max_length=50, null=True)),
                ('facebook_account', models.CharField(max_length=50, null=True)),
                ('apple_account', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('birthday', models.DateField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('forget_password_token', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
