# Generated by Django 3.1.5 on 2021-01-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkshopu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('shop_category_id', models.PositiveIntegerField()),
                ('shop_title', models.CharField(max_length=50)),
                ('shop_icon', models.CharField(max_length=255)),
                ('shop_pic', models.CharField(max_length=255)),
                ('shop_description', models.TextField()),
                ('paypal', models.CharField(max_length=50, null=True)),
                ('visa', models.CharField(max_length=50, null=True)),
                ('master', models.CharField(max_length=50, null=True)),
                ('apple', models.CharField(max_length=50, null=True)),
                ('android', models.CharField(max_length=50, null=True)),
                ('is_ship_free', models.CharField(default='N', max_length=1, null=True)),
                ('ship_by_product', models.CharField(default='N', max_length=1, null=True)),
                ('ship_free_quota', models.PositiveIntegerField(null=True)),
                ('fix_ship_fee', models.PositiveIntegerField(null=True)),
                ('fix_ship_fee_from', models.PositiveIntegerField(null=True)),
                ('fix_ship_fee_to', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_shop_category', models.CharField(max_length=50)),
                ('e_shop_category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
