# Generated by Django 3.1.5 on 2021-01-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkshopu', '0002_shop_shop_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop_Category',
            new_name='Shop_Categories',
        ),
        migrations.RenameModel(
            old_name='Shop',
            new_name='Shops',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
