# Generated by Django 3.1.5 on 2021-01-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkshopu', '0003_auto_20210118_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
        migrations.RenameModel(
            old_name='Shop_Categories',
            new_name='Shop_Category',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
